apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - operator/podsecuritypolicy-operator.yaml
  - kubernetes-monitoring/podsecuritypolicy-kubernetes-monitoring.yaml
  - routing/podsecuritypolicy-routing.yaml
  - metrics/podsecuritypolicy-metrics.yaml
  - oneagent/podsecuritypolicy-oneagent.yaml
  - oneagent/podsecuritypolicy-oneagent-unprivileged.yaml
  - oneagent/role-oneagent.yaml
  - oneagent/role-oneagent-unprivileged.yaml
  - oneagent/rolebinding-oneagent.yaml
  - oneagent/rolebinding-oneagent-unprivileged.yaml
  - webhook/podsecuritypolicy-webhook.yaml
bases:
  - csi
  - ../common
patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: Role
      name: dynatrace-operator
      namespace: dynatrace
    path: operator/role-operator-patch.yaml
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: Role
      name: dynatrace-webhook
      namespace: dynatrace
    path: webhook/role-webhook-patch.yaml

