apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dynatrace-routing
  namespace: dynatrace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dynatrace-routing
subjects:
  - kind: ServiceAccount
    name: dynatrace-routing
    namespace: dynatrace
