apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dynatrace-kubernetes-monitoring
rules:
  - apiGroups:
      - ""
      - batch
      - apps
      - apps.openshift.io
      - config.openshift.io
    resources:
      - nodes
      - pods
      - namespaces
      - deployments
      - replicasets
      - deploymentconfigs
      - replicationcontrollers
      - jobs
      - cronjobs
      - statefulsets
      - daemonsets
      - events
      - resourcequotas
      - pods/proxy
      - nodes/proxy
      - services
      - clusterversions
    verbs:
      - list
      - watch
      - get
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
