apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dynatrace-kubernetes-monitoring
  namespace: dynatrace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dynatrace-kubernetes-monitoring
subjects:
  - kind: ServiceAccount
    name: dynatrace-kubernetes-monitoring
    namespace: dynatrace
