apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dynatrace-webhook
  labels:
    operator: dynakube
    internal.dynatrace.com/component: webhook
subjects:
  - kind: ServiceAccount
    name: dynatrace-webhook
    namespace: dynatrace
roleRef:
  kind: ClusterRole
  name: dynatrace-webhook
  apiGroup: rbac.authorization.k8s.io
