apiVersion: v1
kind: Service
metadata:
  name: dynatrace-webhook
  namespace: dynatrace
  labels:
    dynatrace.com/operator: dynakube
    internal.dynatrace.com/component: webhook
spec:
  selector:
    internal.dynatrace.com/app: webhook
    internal.dynatrace.com/component: webhook
  ports:
    - port: 443
      protocol: TCP
      targetPort: server-port
