apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dynatrace-operator
  namespace: dynatrace
  labels:
    dynatrace: operator
    operator: dynakube
subjects:
  - kind: ServiceAccount
    name: dynatrace-operator
roleRef:
  kind: Role
  name: dynatrace-operator
  apiGroup: rbac.authorization.k8s.io
