apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- operator/clusterrole-operator.yaml
- operator/clusterrolebinding-operator.yaml
- operator/deployment-operator.yaml
- operator/role-operator.yaml
- operator/rolebinding-operator.yaml
- operator/serviceaccount-operator.yaml
- kubernetes-monitoring/clusterrole-kubernetes-monitoring.yaml
- kubernetes-monitoring/clusterrolebinding-kubernetes-monitoring.yaml
- kubernetes-monitoring/role-kubernetes-monitoring.yaml
- kubernetes-monitoring/rolebinding-kubernetes-monitoring.yaml
- kubernetes-monitoring/serviceaccount-kubernetes-monitoring.yaml
- oneagent/serviceaccount-oneagent.yaml
- oneagent/serviceaccount-oneagent-unprivileged.yaml
- webhook/clusterrole-webhook.yaml
- webhook/clusterrolebinding-webhook.yaml
- webhook/deployment-webhook.yaml
- webhook/mutatingwebhookconfiguration.yaml
- webhook/role-webhook.yaml
- webhook/rolebinding-webhook.yaml
- webhook/service.yaml
- webhook/serviceaccount-webhook.yaml
bases:
  - ../crd
  - msgrouting
