kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dynatrace-oneagent-csi-driver
  namespace: dynatrace
subjects:
  - kind: ServiceAccount
    name: dynatrace-oneagent-csi-driver
    namespace: dynatrace
roleRef:
  kind: Role
  name: dynatrace-oneagent-csi-driver
  apiGroup: rbac.authorization.k8s.io
