apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dynatrace-dynakube-oneagent-unprivileged
  namespace: dynatrace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dynatrace-dynakube-oneagent-unprivileged
subjects:
  - kind: ServiceAccount
    name: dynatrace-dynakube-oneagent-unprivileged
    namespace: dynatrace
