kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dynatrace-dynakube-oneagent-unprivileged
  namespace: dynatrace
rules:
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    resourceNames:
      - dynatrace-dynakube-oneagent-unprivileged
    verbs:
      - use
